# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: SpringSecurity
  security:            # \u81EA\u5B9A\u4E49SpringSecurity\u9879\u76EE\u4E2D\u7684\u7528\u6237
    user:
      name: rainlu
      password: 666666

# \u5E94\u7528\u7AEF\u53E3
server:
  port: 8080

